apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
   selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: zaibjahan200/webapp:v1
          ports:
            - containerPort: 80

        - name: apache-exporter
          image: lusotycoon/apache-exporter
          args:
            - "--scrape_uri=http://localhost/server-status?auto"
          ports:
            - containerPort: 9117