apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "devopsterminal-db"
      containers:
        - name: webapp
          image: zaibjahan200/webapp:v1
          # imagePullPolicy: Never
          ports:
            - containerPort: 80